# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nKXfpyvc_NnNr5qBSGiSqj0XJbD_SNfI
"""

# ! pip install git+https://github.com/openai/whisper.git -q
# ! pip install -q transformers sentencepiece

# ! sudo apt update && sudo apt install ffmpeg

import whisper
from transformers import M2M100ForConditionalGeneration, M2M100Tokenizer

model = whisper.load_model("base")

#taking audio file and returning transcription with details
def transcription(audio):
  result = model.transcribe(audio,"translate")
  #print(result)
  return result

def text_translate(msg,model_tr,tokenizer,tr_lang):
  encoded_msg = tokenizer(msg, return_tensors="pt")
  generated_tokens = model_tr.generate(**encoded_msg, forced_bos_token_id=tokenizer.get_lang_id(tr_lang))
  texts_tr = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
  return texts_tr

ckpt = 'facebook/m2m100_418M'
model_tr = M2M100ForConditionalGeneration.from_pretrained(ckpt)
tokenizer_fr = M2M100Tokenizer.from_pretrained(ckpt,src_lang="en", tr_lang="fr")
tokenizer_es = M2M100Tokenizer.from_pretrained(ckpt,src_lang="en", tr_lang="es")
tokenizer_hi = M2M100Tokenizer.from_pretrained(ckpt,src_lang="en", tr_lang="hi")

# raw_msg = transcription(audio)
# text= raw_msg["text"]
# lang=raw_msg["language"]

# if lang != "en":
#   print("Your message has been translated to English")

text ="Hello! How are you?"
num =input("To translate your message to French, press 1. For Spanish, press 2. For Hindi, press 3")

if num=="1":
  texts_tr = text_translate(text,model_tr,tokenizer_fr,tr_lang="fr")
elif num=="2":
  texts_tr = text_translate(text,model_tr,tokenizer_es, tr_lang="es")
elif num=="3":
  texts_tr = text_translate(text,model_tr,tokenizer_hi, tr_lang="hi")
else:
  print("Invalid input, Translation could not proceed")

print(texts_tr[0])