name: containeried-app-translation
run-name: ${{ github.actor }}'s Pull Request Triggered this Workflow
on: [pull_request]

jobs:
  coverage and pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: setting up recent python versions (3.8, 3.9, 3.10)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: updating pip, requirements, pytest
        run: | 
            python3 -m pip install --upgrade pip
            pip install pytest
            if [ -f ./web-app/requirements.txt ]; then pip install -r ./web-app/requirements.txt; fi 
            
      #pip install pylint
            
      #Running commands
      #cd .\web-app
      #.\venv\bin\activate # activate the environment assuming it exists
      #coverage run -m .\tests\*.py
      #coverage report
        
      - name: running test file with coverage
        run: |
            cd ./web-app
            python3 -m coverage run ./tests/*.py 
            python3 -m coverage report > ./web-app/output/app_coverage_results.txt          

      - name: running test with pytest
        run: |
            cd ./web-app
            python3 -m pytest ./tests/*.py

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with: 
          name: app_coverage_results.txt
          path: ./web-app/output/app_coverage_results.txt

    

