name: containeried-app-translation
run-name: ${{ github.actor }}'s Pull Request Triggered this Workflow
on: [pull_request]

jobs:
  building:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: setting up one of two recent python versions (3.8 or 3.11)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: updating pip, requirements, pytest
        run: | 
            python3 -m pip install --upgrade pip
            pip install pytest
            pip install pylint
            if [ -f ./web-app/requirements.txt ]; then pip install -r ./web-app/requirements.txt; fi 
            
      #Running commands
      #cd .\web-app
      #.\venv\bin\activate # activate the environment assuming it exists
      #coverage run -m .\tests\*.py
      #coverage report
        
      - name: running test file with coverage
        run: |
            cd ./web-app
            python3 -m coverage run ./tests/*.py
            python3 -m coverage report           

      - name: running test with pytest
        run: |
            python3 -m pytest ./tests/*.py
    
      - name: linting file
        run: |
            python3 -m pylint $(git ls-files '*.py')

